using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoHub.Migrations
{
    /// <inheritdoc />
    public partial class Countries_Seed : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Clear existing data
            migrationBuilder.Sql("TRUNCATE TABLE dbo.Countries;");
            // Enable IDENTITY_INSERT
            migrationBuilder.Sql("SET IDENTITY_INSERT dbo.Countries ON;");

            // Insert data with explicit identity values
            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "CountryCode", "CountryName", "CreatedOn", "UpdatedOn" },
                values: new object[,]
                {
                    {1,"AF","Afghanistan",DateTime.Now,DateTime.Now},
                    {2,"AL","Albania",DateTime.Now,DateTime.Now},
                    {3,"DZ","Algeria",DateTime.Now,DateTime.Now},
                    {4,"AD","Andorra",DateTime.Now,DateTime.Now},
                    {5,"AO","Angola",DateTime.Now,DateTime.Now},
                    {6,"AG","Antigua and Barbuda",DateTime.Now,DateTime.Now},
                    {7,"AR","Argentina",DateTime.Now,DateTime.Now},
                    {8,"AM","Armenia",DateTime.Now,DateTime.Now},
                    {9,"AU","Australia",DateTime.Now,DateTime.Now},
                    {10,"AT","Austria",DateTime.Now,DateTime.Now},
                    {11,"AZ","Azerbaijan",DateTime.Now,DateTime.Now},
                    {12,"BS","Bahamas",DateTime.Now,DateTime.Now},
                    {13,"BH","Bahrain",DateTime.Now,DateTime.Now},
                    {14,"BD","Bangladesh",DateTime.Now,DateTime.Now},
                    {15,"BB","Barbados",DateTime.Now,DateTime.Now},
                    {16,"BY","Belarus",DateTime.Now,DateTime.Now},
                    {17,"BE","Belgium",DateTime.Now,DateTime.Now},
                    {18,"BZ","Belize",DateTime.Now,DateTime.Now},
                    {19,"BJ","Benin",DateTime.Now,DateTime.Now},
                    {20,"BT","Bhutan",DateTime.Now,DateTime.Now},
                    {21,"BO","Bolivia",DateTime.Now,DateTime.Now},
                    {22,"BA","Bosnia and Herzegovina",DateTime.Now,DateTime.Now},
                    {23,"BW","Botswana",DateTime.Now,DateTime.Now},
                    {24,"BR","Brazil",DateTime.Now,DateTime.Now},
                    {25,"BN","Brunei",DateTime.Now,DateTime.Now},
                    {26,"BG","Bulgaria",DateTime.Now,DateTime.Now},
                    {27,"BF","Burkina Faso",DateTime.Now,DateTime.Now},
                    {28,"BI","Burundi",DateTime.Now,DateTime.Now},
                    {29,"CV","Cabo Verde",DateTime.Now,DateTime.Now},
                    {30,"KH","Cambodia",DateTime.Now,DateTime.Now},
                    {31,"CM","Cameroon",DateTime.Now,DateTime.Now},
                    {32,"CA","Canada",DateTime.Now,DateTime.Now},
                    {33,"CF","Central African Republic",DateTime.Now,DateTime.Now},
                    {34,"TD","Chad",DateTime.Now,DateTime.Now},
                    {35,"CL","Chile",DateTime.Now,DateTime.Now},
                    {36,"CN","China",DateTime.Now,DateTime.Now},
                    {37,"CO","Colombia",DateTime.Now,DateTime.Now},
                    {38,"KM","Comoros",DateTime.Now,DateTime.Now},
                    {39,"CG","Congo (Congo-Brazzaville)",DateTime.Now,DateTime.Now},
                    {40,"CR","Costa Rica",DateTime.Now,DateTime.Now},
                    {41,"HR","Croatia",DateTime.Now,DateTime.Now},
                    {42,"CU","Cuba",DateTime.Now,DateTime.Now},
                    {43,"CY","Cyprus",DateTime.Now,DateTime.Now},
                    {44,"CZ","Czechia (Czech Republic)",DateTime.Now,DateTime.Now},
                    {45,"CD","Democratic Republic of the Congo",DateTime.Now,DateTime.Now},
                    {46,"DK","Denmark",DateTime.Now,DateTime.Now},
                    {47,"DJ","Djibouti",DateTime.Now,DateTime.Now},
                    {48,"DM","Dominica",DateTime.Now,DateTime.Now},
                    {49,"DO","Dominican Republic",DateTime.Now,DateTime.Now},
                    {50,"EC","Ecuador",DateTime.Now,DateTime.Now},
                    {51,"EG","Egypt",DateTime.Now,DateTime.Now},
                    {52,"SV","El Salvador",DateTime.Now,DateTime.Now},
                    {53,"GQ","Equatorial Guinea",DateTime.Now,DateTime.Now},
                    {54,"ER","Eritrea",DateTime.Now,DateTime.Now},
                    {55,"EE","Estonia",DateTime.Now,DateTime.Now},
                    {56,"SZ","Eswatini (Swaziland)",DateTime.Now,DateTime.Now},
                    {57,"ET","Ethiopia",DateTime.Now,DateTime.Now},
                    {58,"FJ","Fiji",DateTime.Now,DateTime.Now},
                    {59,"FI","Finland",DateTime.Now,DateTime.Now},
                    {60,"FR","France",DateTime.Now,DateTime.Now},
                    {61,"GA","Gabon",DateTime.Now,DateTime.Now},
                    {62,"GM","Gambia",DateTime.Now,DateTime.Now},
                    {63,"GE","Georgia",DateTime.Now,DateTime.Now},
                    {64,"DE","Germany",DateTime.Now,DateTime.Now},
                    {65,"GH","Ghana",DateTime.Now,DateTime.Now},
                    {66,"GR","Greece",DateTime.Now,DateTime.Now},
                    {67,"GD","Grenada",DateTime.Now,DateTime.Now},
                    {68,"GT","Guatemala",DateTime.Now,DateTime.Now},
                    {69,"GN","Guinea",DateTime.Now,DateTime.Now},
                    {70,"GW","Guinea-Bissau",DateTime.Now,DateTime.Now},
                    {71,"GY","Guyana",DateTime.Now,DateTime.Now},
                    {72,"HT","Haiti",DateTime.Now,DateTime.Now},
                    {73,"HN","Honduras",DateTime.Now,DateTime.Now},
                    {74,"HU","Hungary",DateTime.Now,DateTime.Now},
                    {75,"IS","Iceland",DateTime.Now,DateTime.Now},
                    {76,"IN","India",DateTime.Now,DateTime.Now},
                    {77,"ID","Indonesia",DateTime.Now,DateTime.Now},
                    {78,"IR","Iran",DateTime.Now,DateTime.Now},
                    {79,"IQ","Iraq",DateTime.Now,DateTime.Now},
                    {80,"IE","Ireland",DateTime.Now,DateTime.Now},
                    {81,"IL","Israel",DateTime.Now,DateTime.Now},
                    {82,"IT","Italy",DateTime.Now,DateTime.Now},
                    {83,"JM","Jamaica",DateTime.Now,DateTime.Now},
                    {84,"JP","Japan",DateTime.Now,DateTime.Now},
                    {85,"JO","Jordan",DateTime.Now,DateTime.Now},
                    {86,"KZ","Kazakhstan",DateTime.Now,DateTime.Now},
                    {87,"KE","Kenya",DateTime.Now,DateTime.Now},
                    {88,"KI","Kiribati",DateTime.Now,DateTime.Now},
                    {89,"KW","Kuwait",DateTime.Now,DateTime.Now},
                    {90,"KG","Kyrgyzstan",DateTime.Now,DateTime.Now},
                    {91,"LA","Laos",DateTime.Now,DateTime.Now},
                    {92,"LV","Latvia",DateTime.Now,DateTime.Now},
                    {93,"LB","Lebanon",DateTime.Now,DateTime.Now},
                    {94,"LS","Lesotho",DateTime.Now,DateTime.Now},
                    {95,"LR","Liberia",DateTime.Now,DateTime.Now},
                    {96,"LY","Libya",DateTime.Now,DateTime.Now},
                    {97,"LI","Liechtenstein",DateTime.Now,DateTime.Now},
                    {98,"LT","Lithuania",DateTime.Now,DateTime.Now},
                    {99,"LU","Luxembourg",DateTime.Now,DateTime.Now},
                    {100,"MG","Madagascar",DateTime.Now,DateTime.Now},
                    {101,"MW","Malawi",DateTime.Now,DateTime.Now},
                    {102,"MY","Malaysia",DateTime.Now,DateTime.Now},
                    {103,"MV","Maldives",DateTime.Now,DateTime.Now},
                    {104,"ML","Mali",DateTime.Now,DateTime.Now},
                    {105,"MT","Malta",DateTime.Now,DateTime.Now},
                    {106,"MH","Marshall Islands",DateTime.Now,DateTime.Now},
                    {107,"MR","Mauritania",DateTime.Now,DateTime.Now},
                    {108,"MU","Mauritius",DateTime.Now,DateTime.Now},
                    {109,"MX","Mexico",DateTime.Now,DateTime.Now},
                    {110,"FM","Micronesia",DateTime.Now,DateTime.Now},
                    {111,"MD","Moldova",DateTime.Now,DateTime.Now},
                    {112,"MC","Monaco",DateTime.Now,DateTime.Now},
                    {113,"MN","Mongolia",DateTime.Now,DateTime.Now},
                    {114,"ME","Montenegro",DateTime.Now,DateTime.Now},
                    {115,"MA","Morocco",DateTime.Now,DateTime.Now},
                    {116,"MZ","Mozambique",DateTime.Now,DateTime.Now},
                    {117,"MM","Myanmar",DateTime.Now,DateTime.Now},
                    {118,"NA","Namibia",DateTime.Now,DateTime.Now},
                    {119,"NR","Nauru",DateTime.Now,DateTime.Now},
                    {120,"NP","Nepal",DateTime.Now,DateTime.Now},
                    {121,"NL","Netherlands",DateTime.Now,DateTime.Now},
                    {122,"NZ","New Zealand",DateTime.Now,DateTime.Now},
                    {123,"NI","Nicaragua",DateTime.Now,DateTime.Now},
                    {124,"NE","Niger",DateTime.Now,DateTime.Now},
                    {125,"NG","Nigeria",DateTime.Now,DateTime.Now},
                    {126,"KP","North Korea",DateTime.Now,DateTime.Now},
                    {127,"MK","North Macedonia",DateTime.Now,DateTime.Now},
                    {128,"NO","Norway",DateTime.Now,DateTime.Now},
                    {129,"OM","Oman",DateTime.Now,DateTime.Now},
                    {130,"PK","Pakistan",DateTime.Now,DateTime.Now},
                    {131,"PW","Palau",DateTime.Now,DateTime.Now},
                    {132,"PA","Panama",DateTime.Now,DateTime.Now},
                    {133,"PG","Papua New Guinea",DateTime.Now,DateTime.Now},
                    {134,"PY","Paraguay",DateTime.Now,DateTime.Now},
                    {135,"PE","Peru",DateTime.Now,DateTime.Now},
                    {136,"PH","Philippines",DateTime.Now,DateTime.Now},
                    {137,"PL","Poland",DateTime.Now,DateTime.Now},
                    {138,"PT","Portugal",DateTime.Now,DateTime.Now},
                    {139,"QA","Qatar",DateTime.Now,DateTime.Now},
                    {140,"RO","Romania",DateTime.Now,DateTime.Now},
                    {141,"RU","Russia",DateTime.Now,DateTime.Now},
                    {142,"RW","Rwanda",DateTime.Now,DateTime.Now},
                    {143,"KN","Saint Kitts and Nevis",DateTime.Now,DateTime.Now},
                    {144,"LC","Saint Lucia",DateTime.Now,DateTime.Now},
                    {145,"VC","Saint Vincent and the Grenadines",DateTime.Now,DateTime.Now},
                    {146,"WS","Samoa",DateTime.Now,DateTime.Now},
                    {147,"SM","San Marino",DateTime.Now,DateTime.Now},
                    {148,"ST","Sao Tome and Principe",DateTime.Now,DateTime.Now},
                    {149,"SA","Saudi Arabia",DateTime.Now,DateTime.Now},
                    {150,"SN","Senegal",DateTime.Now,DateTime.Now},
                    {151,"RS","Serbia",DateTime.Now,DateTime.Now},
                    {152,"SC","Seychelles",DateTime.Now,DateTime.Now},
                    {153,"SL","Sierra Leone",DateTime.Now,DateTime.Now},
                    {154,"SG","Singapore",DateTime.Now,DateTime.Now},
                    {155,"SK","Slovakia",DateTime.Now,DateTime.Now},
                    {156,"SI","Slovenia",DateTime.Now,DateTime.Now},
                    {157,"SB","Solomon Islands",DateTime.Now,DateTime.Now},
                    {158,"SO","Somalia",DateTime.Now,DateTime.Now},
                    {159,"ZA","South Africa",DateTime.Now,DateTime.Now},
                    {160,"KR","South Korea",DateTime.Now,DateTime.Now},
                    {161,"SS","South Sudan",DateTime.Now,DateTime.Now},
                    {162,"ES","Spain",DateTime.Now,DateTime.Now},
                    {163,"LK","Sri Lanka",DateTime.Now,DateTime.Now},
                    {164,"SD","Sudan",DateTime.Now,DateTime.Now},
                    {165,"SR","Suriname",DateTime.Now,DateTime.Now},
                    {166,"SE","Sweden",DateTime.Now,DateTime.Now},
                    {167,"CH","Switzerland",DateTime.Now,DateTime.Now},
                    {168,"SY","Syria",DateTime.Now,DateTime.Now},
                    {169,"TJ","Tajikistan",DateTime.Now,DateTime.Now},
                    {170,"TZ","Tanzania",DateTime.Now,DateTime.Now},
                    {171,"TH","Thailand",DateTime.Now,DateTime.Now},
                    {172,"TL","Timor-Leste",DateTime.Now,DateTime.Now},
                    {173,"TG","Togo",DateTime.Now,DateTime.Now},
                    {174,"TO","Tonga",DateTime.Now,DateTime.Now},
                    {175,"TT","Trinidad and Tobago",DateTime.Now,DateTime.Now},
                    {176,"TN","Tunisia",DateTime.Now,DateTime.Now},
                    {177,"TR","Turkey",DateTime.Now,DateTime.Now},
                    {178,"TM","Turkmenistan",DateTime.Now,DateTime.Now},
                    {179,"TV","Tuvalu",DateTime.Now,DateTime.Now},
                    {180,"UG","Uganda",DateTime.Now,DateTime.Now},
                    {181,"UA","Ukraine",DateTime.Now,DateTime.Now},
                    {182,"AE","United Arab Emirates",DateTime.Now,DateTime.Now},
                    {183,"GB","United Kingdom",DateTime.Now,DateTime.Now},
                    {184,"US","United States",DateTime.Now,DateTime.Now},
                    {185,"UY","Uruguay",DateTime.Now,DateTime.Now},
                    {186,"UZ","Uzbekistan",DateTime.Now,DateTime.Now},
                    {187,"VU","Vanuatu",DateTime.Now,DateTime.Now},
                    {188,"VA","Vatican City",DateTime.Now,DateTime.Now},
                    {189,"VE","Venezuela",DateTime.Now,DateTime.Now},
                    {190,"VN","Vietnam",DateTime.Now,DateTime.Now},
                    {191,"YE","Yemen",DateTime.Now,DateTime.Now},
                    {192,"ZM","Zambia",DateTime.Now,DateTime.Now},
                    {193,"ZW","Zimbabwe",DateTime.Now,DateTime.Now}

                });

            // Disable IDENTITY_INSERT
            migrationBuilder.Sql("SET IDENTITY_INSERT dbo.Countries OFF;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Clear existing data
            migrationBuilder.Sql("TRUNCATE TABLE dbo.Countries;");
        }
    }
}
